### ISSUE TITLE
I am not able to compile the code

### ISSUE THREAD

**Issue by MysteriousHercules** [Aftnet/LibretroRT#6] opened 2017-05-31 18:40 UTC
Every time I try to compile the code, I get an error saying "libretro.winmd" could not be found. I am not sure If that means I am supposed to download something?

Also, Am I supposed to choose libretroet.test, or just test.

**Comment by albertofustinoni** [comment] 2017-05-31 23:47
Are you compiling for "Any CPU"? You need to select x86, x64 or ARM as the architecture.

For the front end, it's just Test

**Comment by MysteriousHercules** [comment] 2017-06-01 01:25
I chose x64, Here is a screenshot: 
![libretro compile](https://cloud.githubusercontent.com/assets/28547332/26660709/902d6aac-462e-11e7-8da0-576aa5067619.png)

**Comment by wiired24** [comment] 2017-06-01 13:58
I'm getting the same issue as well. I chose Test as the startup Project. I have x64 set as the targeted architecture and when I build it gives me 400+ errors related to  "file cannot be found"

**Comment by albertofustinoni** [comment] 2017-06-01 14:02
@wiired24 Try doing `git submodule update --remote` in a command prompt in the project's solution folder.

**Comment by albertofustinoni** [comment] 2017-06-01 14:03
@MysteriousHercules I see no errors in that screenshot though.

**Comment by wiired24** [comment] 2017-06-01 14:03
Thanks I'll done a fresh git clone and I'll try that in Git Bash :)

**Comment by wiired24** [comment] 2017-06-01 14:25
Tried doing a submodule update but I'm still getting the same errors.

"Metadata file 'C:\Users\vanit\LibretroRT\x64\Debug\FCEUMMRT\FCEUMMRT.winmd' could not be found	LibretroRT.Test	C:\Users\vanit\LibretroRT\LibretroRT.Test\CSC"  <- Lots of these

**Comment by albertofustinoni** [comment] 2017-06-01 14:27
Does it work if you build for x86? If so, repair your installation of Visual Studio 2017 (if you haven't updated to the latest version do it and try again)

**Comment by MysteriousHercules** [comment] 2017-06-01 19:52
I have the latest visual studio 2017, and I do have monogame  because I use it with Unity. I am guessing it has to do which file I set as startup? But you know the code more than I do. 

On an unrelated topic, good job on the UWP project, I have noticed you added nestopia and snes9x, do they work?

**Comment by albertofustinoni** [comment] 2017-06-01 23:09
In that case, I really have no idea why it's not building for you.
As unhelpful as it sounds (and I do apologize), it works on both machines I use for development.

Nestopia doesn't really work well, which is why I added FCEUMM as well and use it instead.
Snes9x worked fine in my limited testing (start of Yoshi's Island)

**Comment by MysteriousHercules** [comment] 2017-06-01 23:15
That is good to hear. I do have a question though. If you look at the screenshot I posted. In the solution explorer, I had libretroRT.test selected when compiling and creating package. Am I supposed to select something else. Also, Am I supposed to have some sort of dependency?

**Comment by wiired24** [comment] 2017-06-02 01:09
@albertofustinoni @MysteriousHercules   I figured out what the issue is. It's because when you do a git clone and you clone the repo to your computer the  "src" that is supposued to be included in each core does not get cloned.  For example say you do a git clone of LibretroRT and you were to look in the FCEUMM directory if you clicked on the folder that was labelled as "src" you would find that it's empty. Same with all the other cores. @albertofustinoni  It's working for you of course because you already have the source code for each of the cores on your testing machines. But when users/devs do a git clone of this repo to their computer they are not getting the necessary source code files for each respective core that they would need in order for LibreretroRT to build.

**Comment by MysteriousHercules** [comment] 2017-06-02 09:59
@wiired24  It is awesome to hear that you got it wiired24, How did you resolve the issue. Where did you find the missing source code?

**Comment by albertofustinoni** [comment] 2017-06-02 11:29
@wiired24 @MysteriousHercules The source code is not in my repository because I include it as [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). When cloning my repo, you need to add `--recursive` to the command or clone from Team Explorer in Visual Studio (easiest).

If you copied the source from other repos manually, I'd strongly recommend deleting the folder and starting again to avoid issues.

The roms are not included in the repository for the obvious legal issues you mentioned: the folder is included in gitignore to make sure those files never leave the local environment and Visual studio failing the build because of those missing files after you clone is very much working as intended. Given that the project using them is unit tests for the cores, you can safely disable it.

I am well aware of the UI issue: Retrix as it is now is a hack job and the barest minimum I could get away with to test the recompiled cores and my framework.

Finally, I would recommend against working on the project with the intention to merge back: I plan on getting rid of the RetriX front end as it is now and re implement video rendering in a way that can use the Libretro-gl portion of the API to allow for using hardware accelerated cores. I would end up not accepting your pull requests.

**Comment by wiired24** [comment] 2017-06-02 13:45
Thanks for the rather lengthy response. 
1. Didn't know I had to add --recursive  (I've only worked with Git/Github for a few months)
2. With regards to the Rom issue how would i go about disabling it? 
3. I figured you were aware of the issue but I just wanted to let ya know and get your feedback on it
4. That's awesome to hear. I'm  glad that you're going to be moving towards hardware accelerated cores.
   Should provide for much nicer results :)

**Comment by MysteriousHercules** [comment] 2017-06-02 21:16
Alright, if I can help with anything you guys want, let me know. I assume there is no need to work on the front end since it is being replaced.

**Comment by wiired24** [comment] 2017-06-02 23:34
@MysteriousHercules  Yep That's what the man said 

You can still help by testing and raising an issue if you find any bugs

**Comment by MysteriousHercules** [comment] 2017-06-03 00:03
@wiired24  I have been a lot of detective work analyzing the code and I understood a lot of it. if you are looking for how to change the rom directory. go to libretro/libretroRT.test/cores.

And then you will find a bunch of scripts for each core that is defining the name of each rom it is looking for.

**Comment by MysteriousHercules** [comment] 2017-06-03 00:23
I managed to edit the code, so that it can compile and build without needing to have anything in the rom directory. Is it ok if I make a commit? so that people who download the source code here can run the emulator without having any rom problems like the ones I encountered.

**Comment by albertofustinoni** [comment] 2017-06-03 01:08
I'd rather not. You don't need to build the project that includes the rom to use RetriX. Just right click it in Solution Explorer and unload it.

That project does some sanity checks by running the cores against roms and is useful when developing.

**Closed** 2017-06-16 00:11 UTC
